name: Upload to S3 on Merge

on:
  push:
    branches:
      - master  # Specify the branch to trigger the action

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the repository
      
    - name: Check if specific file has changed
      id: check_file
      run: |
        # Check if the file has changed in the last commit
        if git diff --name-only HEAD^ HEAD | grep 'src/main/resources/data.txt'; then
          echo "File changed, proceeding with upload"
          echo "::set-output name=file_changed::true"
        else
          echo "File not changed, skipping upload"
          echo "::set-output name=file_changed::false"
        fi

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change to your region

    - name: Upload file to S3
      run: |
        aws s3 cp GitEvent/src/main/resources/ApplicationResource.properties s3://resourcebundle/${{ github.ref_name }}/ApplicationResource.properties --region us-east-1
